### ISSUE TITLE
Build Environment

### ISSUE THREAD

**Issue by djtulan** [KimJorgensen/easyflash#2]
Could you please tell me which version of **cc65**, **acme** and **exomizer** you use, to build the init?
And what version of gcc to build the tools!

best regards
Tulan

**Comment by KimJorgensen** [comment]
Sure, I used this guide to get started https://www.c64-wiki.de/wiki/EasyFlash³/Sourcecode_kompilieren
It's in German, but hopefully you'll understand it.

**Comment by djtulan** [comment]
Thank you, that helped me a lot!
