### ISSUE TITLE
Easy Transfer?

### ISSUE THREAD

**Issue by DanHolli123** [KimJorgensen/easyflash#4]
The device firmware and software has been updated, but what about the software, also I can't seem to get ANYTHING working over usb (SD2IEC on it's way for that)

**Comment by KimJorgensen** [comment]
Did you change the jumper position after updating the firmware?

**Comment by DanHolli123** [comment]
I wasn't meaning the device itself, I was meaning the actual software/firmware has and was released. I'm wondering if it will be updated. also USB on my device doesn't matter much since I wiped the menu anyway so i no longer have easy flash (unless I can use a slightly older version on floppy to assist with the process)

**Comment by DanHolli123** [comment]
as for the jumper positions, they are all in the data area as I've heard recommended

**Comment by KimJorgensen** [comment]
If you are asking if EasyTransfer needs to be updated, the answer is no. I made no changes to the USB protocol, so the EasyTransfer should continue to work.
It is possible to use an older version of EF3 menu to upgrade to version 1.3.1 via USB, see http://skoe.de/easyflash/doku.php?id=writecrtusb

**Comment by DanHolli123** [comment]
Ok, I think that that sounds great, I do have a suggestion for it but I'll make a separate topic for it.
