### ISSUE TITLE
USB not working

### ISSUE THREAD

**Issue by DanHolli123** [KimJorgensen/easyflash#6]
I've been having trouble doing much with the USB interface, I'm not sure if this is the best place, but it is the only place I know of that is still active for this hardware. 
It is the most recent "official" version of firmware 1.1.1 I believe it is.

I can get a small program through by spamming the command line commands done by having it entered and run pressing control+c to kill it if it doesn't go, then pressing up and enter to quickly re-enter the command and run it and repeating that untill it goes.

anything larger or more complex just won't work, I can't write a disk image, nor can I flash CRTs.

I have all the jumpers in the data positions and untill I get my SD2IEC running again or the new one arrives, I'm stuck with the USB interface

**Comment by KimJorgensen** [comment]
I can only offer general advice: Do not use a USB hub, try a different USB cable, try a different PC.
If you are looking for support, I would try [lemon64](https://www.lemon64.com/forum/viewforum.php?f=1) or [forum64](https://www.forum64.de/index.php?board/292-easyflash/). Forum64 is German, but most seem willing to answer in English.

**Comment by DanHolli123** [comment]
OK, thank you for the help, I'll try there later.

I've never used a hub, tried several cords, and used 3 computers, could just be old or corrupted firmware, I'll install your firmware when I get my SD2IEC running again.

**Comment by KimJorgensen** [comment]
Sounds more like a hardware issue to me, maybe a bad solder joint?
Good luck
