### ISSUE TITLE
easyprog 1.7.1 Expert auto-int broken

### ISSUE THREAD

**Issue by lolof70** [KimJorgensen/easyflash#7]
Hi,

The mode Expert Auto-INT to write all crt at once is broken in easyprog 1.8.1 (CPLD 1.2.1) while it's working in official last version with official CPLD.

It's doing the job endless and never stop. After to have written auto-7, it start over again from auto-0....

Is this a known bug ?

Thank you

EDIT 

Just discovered that my auto-7 was corrupted and that's surely the reason it's start over again.

**Comment by lolof70** [comment]
Finally tried again with a valid auto-7.CRT and this fonction in Easyprog 1.8.1 is definitively broken.

You can reproduce this while using the AUTO-int fonction in expert menu to write all the crt at once on the EF3......

**Comment by KimJorgensen** [comment]
Hi,
I'm not able to reproduce this behaviour. I just tried twice with two different set of CRTs and the program stops after auto-7 as expected.
/Kim

**Comment by lolof70** [comment]
Hi,

Strange, I did not had this problem with the old version.
I had this with different CRT sets and with 3 differents EF3.

I will try this again with another SD card. 

Can it be it’s coming from something with the new firmware/software in combination with my SD2IEC ?

I’ve this one :

https://www.ebay.com/itm/NEW-2018-SD2IEC-SD-Card-Reader-for-Commodore-64-128-VIC20-1541-C64-C128/163086890817

Seb

**Comment by KimJorgensen** [comment]
Did you verify all the CRTs in VICE, or did you try to flash the individually? Especially pay attention to the size of the CRTs, they should not be bigger than one megabyte.

There was no change regarding reading from SD2IEC in the new version, but it is possible that I made a mistake somewhere. You could try to downgrade the firmware and EasyProg and see if the problem persists.

**Comment by lolof70** [comment]
Hi,

I did some more testing….

I tested the same procedure with CPLD 1.2.1 and also with CPLD 1.1.1   With known working CRT set.
All results are same with both CPLD versions.

It can write all slots and stop after the last slot (7) is written if I use the easyprog version 1.7.0  It’s as it should be. 
Note that I could not find a 1.7.1 version in Skoe download page.

Now if I am using the easyprog Version 1.8.1, it writes all slot from 0-7 and does never stop. It start over again when slot 7 is finished……

There should be a bug somewhere in easyprog 1.8.1  but it’s very curious you can’t reproduce it. Maybe it’s something related to easyprog 1.8.1 and my SD2IEC…..

For me it’s 200% sure there is something, I can reproduce this each time I am using easyprog 1.8.1 with different CRT sets and with both CPLD 1.1.1 and 1.2.1 firmware.

Regards

Seb

**Comment by KimJorgensen** [comment]
I believe that EasyProg 1.7.1 only exist in source code form and never was released. But I did notice the following in the CHANGES file for that version:
```Auto test + init executes the torture test before flashing```
Is that what is confusing you? The torture test is runs through all slots and when it is done the CRTs are flashed.
The torture test can be canceled using RUN/STOP

**Comment by lolof70** [comment]
Oh yes, that’s probably this !!!

The 1.7.0 is directly flashing all the slot, no othe test are perfomed…..

When updating to the 1.8.1, I saw it flashing all the slots and starts over again. I thought it was wrong as I never saw this before.
No I understand, that’s the 1.7.0 that does differently by not doing the torture test.

I will try again without stoping the process or using the RUN/STOP test to jump directly to the flashing slots process.

It seems you lost your time with me. But I would have not figured this out myself as I never saw the 1.7.1 version or the change log….

Thank you and sorry….

Seb

**Comment by KimJorgensen** [comment]
I assume this is resolved, otherwise feel free to report a new issue.
/Kim

**Comment by lolof70** [comment]
Hi,

Sorry, I forgot to reply you.
It's 100% working. As you said, I just had to skip the stress test with
run/stop.

I feel a bit stupid.....

Thanks.

Regards

Seb

Le mar. 16 avr. 2019 à 08:09, Kim Jørgensen <notifications@github.com> a
écrit :
